---
- set_fact:
    os_type: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"

- include: prepare.yml env={{item}}
  with_items: "{{ install_envs }}"

- include: install.yml env={{item}}
  with_items: "{{ install_envs }}"
