---
galaxy_info:
  author: gano
  description: install anyenv and each envs
  license: MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - 6
        - 7
  galaxy_tags:
    - centos
    - anyenv
    - rbenv
    - git

dependencies: [ gano2018.ansible_os_init, gano2018.ansible_git ]
